import Image from 'next/image';
import SiteShell from '../../../components/SiteShell';
import {programAreas} from '../../../data/content';
export const metadata={title:'Programs'};
const immigrantGallery=[
 ['/images/programs/new-immigrant-parent.webp','Parent education for new immigrant families'],
 ['/images/programs/new-immigrant-training.webp','2024 training for program staff'],
 ['/images/programs/new-immigrant-case.webp','2025 case discussion meeting'],
 ['/images/programs/new-immigrant-career.webp','2026 career seminar for new immigrant communities']
];
export default function Page(){return <SiteShell lang="en"><section><div className="container"><div className="breadcrumb">Home / Programs</div><div className="page-intro"><div className="eyebrow">Programs & Services</div><h1>From health education to social recovery</h1><p className="lead">Across different periods, the Association's work has covered addiction health, youth and families, new immigrant communities, harm reduction research and professional exchange.</p></div><div className="cards cards-2">{programAreas.map(p=><div className="card" key={p.title}><div className="kicker">{p.en}</div><h3>{p.en}</h3><p>{p.textEn}</p></div>)}</div></div></section><section className="section-soft"><div className="container"><div className="section-head"><div><div className="eyebrow">Gender-responsive recovery</div><h2>Support for women who use drugs</h2></div><p>Association project records from 2021–2022 describe a community rehabilitation model built around case management, health education, counseling, psychotherapy, and coordinated medical, justice, employment, parenting and social-service resources.</p></div><div className="cards"><div className="card"><h3>Assessment & case management</h3><p>Needs were assessed across substance use, mental health, daily life, family and community support, followed by individualized service planning.</p></div><div className="card"><h3>Cross-sector coordination</h3><p>Medical, justice, counseling, welfare, employment and parenting resources were connected to reduce gaps in care.</p></div><div className="card"><h3>Gender- and trauma-responsive care</h3><p>The model recognized trauma, intimate relationships, caregiving responsibilities and social roles as important parts of recovery.</p></div></div></div></section><section><div className="container"><div className="section-head"><div><div className="eyebrow">New immigrant families</div><h2>Family and community support</h2></div><p>Association records document work in family visits, parent education, early-intervention support for children, staff training, case discussion and career support.</p></div><div className="photo-grid">{immigrantGallery.map(([src,cap])=><figure key={src}><Image src={src} width={900} height={675} alt={cap}/><figcaption>{cap}</figcaption></figure>)}</div><div className="meta">Images were supplied by the Association for this website project. No identifiable client case information is published alongside the photographs.</div></div></section></SiteShell>}
