import SiteShell from '../../components/SiteShell';
export const metadata={title:'成癮與健康知識',description:'以健康、實證與不污名的方式理解物質使用、物質使用疾患、治療、復元與家庭支持。',alternates:{canonical:'/knowledge',languages:{'zh-Hant':'/knowledge','en':'/en/knowledge'}}};
const Ref=({href,children})=><a className="source-link" target="_blank" rel="noreferrer" href={href}>{children} ↗</a>;
export default function Page(){return <SiteShell><section><div className="container article-layout"><aside className="article-nav"><strong>本頁內容</strong><a href="#basics">理解物質使用</a><a href="#treatment">治療原則</a><a href="#recovery">復元</a><a href="#youth">青少年與家庭</a><a href="#help">何時尋求協助</a><a href="#sources">主要來源</a></aside><article className="prose"><div className="breadcrumb">首頁 / 成癮與健康知識</div><div className="article-intro"><div className="eyebrow">Knowledge</div><h1>成癮與健康知識</h1><p className="lead">以健康、實證與不污名的方式，理解物質使用、物質使用疾患、治療與復元。</p></div>
<div className="key-points"><strong>先記住三件事</strong><ul><li>使用物質不等於一定有「成癮」；是否形成健康問題，需要看使用型態、失控程度、傷害與生活功能。</li><li>物質使用疾患是可以評估與治療的健康狀況，不是道德失敗。</li><li>越早得到合適、持續且個別化的支持，越有機會改善健康與生活功能。</li></ul></div>
<h2 id="basics">理解物質使用：重點是風險、傷害與功能</h2><p>WHO 在 ICD-11 與相關公共衛生工作中，將藥物使用相關問題放在健康照護框架。物質使用可能從偶發使用、較高風險使用，到有害使用型態與依賴，程度並不相同。實際判斷不應只看「有沒有使用」，而應綜合頻率、劑量、情境、身心健康、控制能力、社會功能與是否持續造成傷害。</p><p>如果物質使用已影響睡眠、情緒、工作／就學、人際、財務、身體健康，或曾出現過量、感染、事故、戒斷或強烈渴求，就值得接受專業評估。</p>
<h2 id="treatment">治療不是只有一種，也不應以羞辱或強迫為核心</h2><p>WHO 與 UNODC 的國際治療標準主張，藥物使用疾患的照護應具備實證基礎、倫理、人權保障與個別化，並盡可能整合到一般健康與社會服務。治療通常不是一次性的事件，而可能是持續一段時間的照護歷程。</p><div className="cards cards-2 inline-cards"><div className="card"><h3>可能包含的照護元素</h3><p>完整評估、心理社會介入、符合適應症的藥物治療、身心共病照護、感染疾病篩檢與治療、家庭支持、社福與就業資源、持續追蹤。</p></div><div className="card"><h3>好的服務應做到</h3><p>尊重隱私、避免污名、說明治療選項與風險、共同設定目標，並依個人需求調整強度與服務組合。</p></div></div>
<h2 id="recovery">復元是一段過程，不只用「有沒有完全停止」衡量</h2><p>對不同的人，復元目標可能不同：減少高風險使用、改善睡眠與心理健康、避免過量、回到工作或學校、重建家庭關係、持續接受治療，或最終停止使用。把進步拆成可達成的階段，通常比「一次成功或失敗」更符合長期健康照護的現實。</p><p>復發或再次使用不代表所有努力歸零，而是需要重新檢視觸發因素、支持系統、治療強度與安全計畫的訊號。若曾在停用後再次使用，耐受性可能下降，部分藥物的過量風險會因此增加。</p>
<h2 id="youth">青少年與家庭：有效預防不只是一場反毒演講</h2><p>WHO/UNODC 的國際預防標準強調，以年齡與發展階段為基礎，長期培養家庭支持、親職能力、學校連結、社會情緒能力與健康環境，比單純依靠恐嚇、羞辱或只提供資訊更符合實證方向。</p><div className="callout"><strong>給家長與重要他人的溝通原則</strong><p>先問發生了什麼、目前最擔心什麼，再談風險與界線；避免在高度衝突或對方意識不清時進行長篇說教。若已出現持續使用、身心症狀、失學／失業、法律問題或家庭功能明顯受影響，應及早尋求專業協助。</p></div>
<h2 id="help">什麼情況需要盡快求助？</h2><ul><li><strong>緊急：</strong>意識不清、呼吸變慢或困難、抽搐、胸痛、嚴重高熱、極度混亂、失去反應等，應立即尋求緊急醫療協助。</li><li><strong>近期安排評估：</strong>反覆失控使用、明顯戒斷、強烈渴求、工作或就學受影響、憂鬱焦慮惡化、曾發生過量、感染風險升高，或本人／家屬已感到難以負荷。</li><li><strong>家屬也可以先求助：</strong>即使當事人尚未準備接受治療，家屬仍可先尋求諮詢，學習降低衝突、辨識危險與建立支持界線。</li></ul>
<div className="notice"><strong>醫療聲明：</strong> 本頁是一般衛教，不做個別診斷或用藥建議。突然停用某些物質可能有醫療風險；若有規律大量使用、嚴重身心共病、懷孕或正在使用多種藥物，請由醫療專業人員評估。</div>
<h2 id="sources">主要參考來源</h2><ul className="references"><li><Ref href="https://www.who.int/publications/i/item/international-standards-for-the-treatment-of-drug-use-disorders">WHO/UNODC — International Standards for the Treatment of Drug Use Disorders (2020)</Ref></li><li><Ref href="https://www.who.int/activities/improving-prevention-and-treatment-for-drug-use-disorders">WHO — Improving prevention and treatment for drug use disorders</Ref></li><li><Ref href="https://www.unodc.org/documents/prevention/UNODC-WHO_2018_prevention_standards_E.pdf">WHO/UNODC — International Standards on Drug Use Prevention (2018)</Ref></li></ul><div className="meta">最後更新：2026-10-05 · 內容定位：一般健康教育，不取代醫療專業評估。</div></article></div></section></SiteShell>}
