import Image from 'next/image';
import Link from 'next/link';
import SiteShell from '../components/SiteShell';
import {organization} from '../data/content';
export const metadata={title:'首頁'};
export default function Home(){return <SiteShell><>
<section className="hero hero-premium"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow">Health · Recovery · Harm Reduction</div><h1>讓健康資訊更可信，<br/>讓支持更靠近人。</h1><p className="lead">{organization.nameZh}以健康促進為核心，推動成癮照護、復元支持與減害教育。我們相信，每個人都有權利在尊嚴、理解與實證支持中，走向更健康的生活。</p><div className="actions"><Link className="btn primary" href="/knowledge">了解成癮與健康</Link><Link className="btn secondary" href="/harm-reduction">認識減害</Link></div><div className="trust-row"><span>✓ 中英雙語</span><span>✓ 實證來源</span><span>✓ 不污名溝通</span></div></div><div className="hero-visual"><div className="hero-art-shell"><Image className="hero-art" src="/images/illustrations/hero-home.svg" width={1199} height={675} alt="台灣社區健康、復元與支持的原創插畫" priority/><div className="hero-message"><strong>每個人，都有權利過平凡而快樂的生活。</strong><span>雀樂協會的核心信念</span></div></div></div></div></section>
<section className="quick-section"><div className="container"><div className="quick-grid"><Link href="/knowledge" className="quick-card"><span>01</span><strong>我想了解成癮與復元</strong><small>從健康觀點理解物質使用疾患、治療與復元。</small></Link><Link href="/harm-reduction" className="quick-card"><span>02</span><strong>我想了解減害</strong><small>以實證、尊嚴和降低傷害為核心的公共衛生方法。</small></Link><Link href="/programs" className="quick-card"><span>03</span><strong>我是家屬、教師或專業者</strong><small>查看雀樂的方案領域與可參考的專業資源。</small></Link></div></div></section>
<section className="section-soft"><div className="container"><div className="section-head"><div><div className="eyebrow">Our approach</div><h2>不只談「不要使用」，而是一起把健康做得更好。</h2></div><p>WHO 的健康促進觀點強調提升人們掌握與改善自身健康的能力。雀樂以此為基礎，結合成癮治療、復元與減害的國際實證，轉化成可理解、可行動的健康資訊。</p></div><div className="cards"><div className="card featured-card"><div className="kicker">健康促進</div><h3>增能，而不是恐嚇</h3><p>關注保護因子、健康識能、家庭與社區支持，讓人有能力做出更安全、更健康的選擇。</p><Link href="/knowledge" className="text-link">閱讀健康知識 →</Link></div><div className="card featured-card"><div className="kicker">復元支持</div><h3>治療與復元可以個別化</h3><p>成癮照護可結合心理社會介入、醫療、家庭支持、持續照護與社會復歸，不以單一路徑定義成功。</p><Link href="/knowledge#recovery" className="text-link">了解治療與復元 →</Link></div><div className="card featured-card"><div className="kicker">減害</div><h3>先降低可避免的傷害</h3><p>以健康、人權、尊嚴與實證為原則，降低藥物使用與相關環境可能造成的健康與社會風險。</p><Link href="/harm-reduction" className="text-link">認識減害原則 →</Link></div></div></div></section>
<section><div className="container about-band"><div><div className="eyebrow">About us</div><h2>關於雀樂</h2><p className="lead compact">協會成立於 2008 年 3 月並經內政部立案。歷年工作涵蓋成癮健康教育、家庭與社區支持、青少年與校園預防、新住民家庭服務、減害研究及專業交流。</p><div className="actions"><Link className="btn primary" href="/about">認識雀樂</Link><Link className="btn secondary" href="/programs">方案與服務</Link></div></div><Image src="/images/logo-with-name.webp" width={800} height={500} alt="社團法人台灣雀樂協會識別標誌"/></div></section>
<section className="section-soft"><div className="container"><div className="section-head"><div><div className="eyebrow">Evidence first</div><h2>衛教內容，清楚標示依據與更新時間。</h2></div><p>我們優先採用 WHO、WHO/UNODC、Harm Reduction International 等可追溯來源；國際做法涉及台灣法規或服務可近性時，會明確標示在地差異。</p></div><div className="evidence-strip"><div><strong>WHO</strong><span>健康促進與公共衛生</span></div><div><strong>WHO / UNODC</strong><span>成癮治療與預防標準</span></div><div><strong>HRI</strong><span>減害、人權與尊嚴</span></div></div></div></section>
<section><div className="container"><div className="notice"><strong>健康資訊提醒：</strong> 本網站提供一般健康教育與資源整理，不取代個別醫療診斷、治療或緊急服務。若出現意識不清、呼吸困難、胸痛、抽搐或其他急性危險症狀，請立即尋求緊急醫療協助。</div></div></section>
</></SiteShell>}