import Image from 'next/image';
import Link from 'next/link';
import SiteShell from '../../components/SiteShell';
import {organization} from '../../data/content';
export const metadata={title:'Home',description:'Official website of Taiwan Happiness Association: health promotion, addiction health education, recovery support and harm reduction.',alternates:{canonical:'/en',languages:{'zh-Hant':'/','en':'/en'}}};
export default function Home(){return <SiteShell lang="en"><>
<section className="hero hero-premium"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow">Health · Recovery · Harm Reduction</div><h1>Trusted health information. Support that stays close to people.</h1><p className="lead">{organization.nameEn} promotes health, recovery support and evidence-informed harm reduction. We believe everyone deserves access to dignity, understanding and practical support for a healthier life.</p><div className="actions"><Link className="btn primary" href="/en/knowledge">Addiction & health</Link><Link className="btn secondary" href="/en/harm-reduction">Harm reduction</Link></div><div className="trust-row"><span>✓ Bilingual</span><span>✓ Evidence-informed</span><span>✓ Non-stigmatizing</span></div></div><div className="hero-visual"><div className="hero-art-shell"><Image className="hero-art" src="/images/illustrations/hero-home.svg" width={1199} height={675} alt="Original illustration about community health, recovery and support" priority/><div className="hero-message"><strong>Everyone deserves an ordinary, joyful life.</strong><span>Our core belief</span></div></div></div></div></section>
<section className="quick-section"><div className="container"><div className="quick-grid"><Link href="/en/knowledge" className="quick-card"><span>01</span><strong>Understand addiction & recovery</strong><small>Health-focused information on substance use disorders, treatment and recovery.</small></Link><Link href="/en/harm-reduction" className="quick-card"><span>02</span><strong>Understand harm reduction</strong><small>Evidence, dignity and practical risk reduction in public health.</small></Link><Link href="/en/programs" className="quick-card"><span>03</span><strong>Families & professionals</strong><small>Explore our program areas and professional resources.</small></Link></div></div></section>
<section className="section-soft"><div className="container"><div className="section-head"><div><div className="eyebrow">Our approach</div><h2>Health promotion is more than telling people what not to do.</h2></div><p>Our communication draws on international health-promotion, addiction-treatment and harm-reduction evidence, translating it into practical, respectful and understandable information.</p></div><div className="cards"><div className="card featured-card"><div className="kicker">Health promotion</div><h3>Build capacity, not fear</h3><p>Strengthen health literacy, protective factors and support across families, schools and communities.</p></div><div className="card featured-card"><div className="kicker">Recovery</div><h3>Care can be individualized</h3><p>Treatment may combine psychosocial care, health services, family support, continuing care and social reintegration.</p></div><div className="card featured-card"><div className="kicker">Harm reduction</div><h3>Reduce preventable harm first</h3><p>Protect health and dignity while lowering barriers to effective services.</p></div></div></div></section>
<section><div className="container about-band"><div><div className="eyebrow">About us</div><h2>About the Association</h2><p className="lead compact">Founded in March 2008 and formally registered in Taiwan, our work has included addiction health education, family and community support, youth prevention, new immigrant family services, harm reduction research and professional exchange.</p><div className="actions"><Link className="btn primary" href="/en/about">About us</Link><Link className="btn secondary" href="/en/programs">Programs</Link></div></div><Image src="/images/logo-with-name.webp" width={800} height={500} alt="Taiwan Happiness Association identity"/></div></section>
<section><div className="container"><div className="notice"><strong>Health information notice:</strong> This website provides general education and resource navigation. It does not replace individualized medical diagnosis, treatment or emergency care.</div></div></section>
</></SiteShell>}