import SiteShell from '../../components/SiteShell';
export const metadata={title:'減害 Harm Reduction'};
const Ref=({href,children})=><a className="source-link" target="_blank" rel="noreferrer" href={href}>{children} ↗</a>;
export default function Page(){return <SiteShell><section><div className="container article-layout"><aside className="article-nav"><strong>本頁內容</strong><a href="#definition">什麼是減害</a><a href="#principles">核心原則</a><a href="#services">國際實證措施</a><a href="#stigma">污名與可近性</a><a href="#taiwan">台灣情境</a><a href="#sources">主要來源</a></aside><article className="prose"><div className="breadcrumb">首頁 / 減害</div><div className="eyebrow">Harm Reduction</div><h1>減害：先降低可避免的傷害，讓健康支持更容易抵達。</h1><p className="lead">減害不是鼓勵藥物使用，也不是放棄治療；它是一套以公共衛生、實證、人權與尊嚴為基礎的方法。</p>
<h2 id="definition">什麼是減害？</h2><p>Harm Reduction International 將減害描述為：降低與藥物使用、藥物政策及相關法律可能造成之健康、社會與法律負面影響的政策、方案與實務。它強調正向改變，以及不以評價、強迫、歧視或「必須先停止使用」作為取得支持的前提。</p><p>這與治療並不衝突。對一些人，停止使用是明確目標；對另一些人，第一步可能是避免過量、降低感染、改善睡眠、接受醫療、減少高風險情境或重新與支持系統連結。</p>
<h2 id="principles">四個核心原則</h2><div className="cards cards-2 inline-cards"><div className="card"><h3>實證</h3><p>優先採用經研究支持、可監測效果與安全性的介入，不以恐懼或未經驗證的做法取代專業服務。</p></div><div className="card"><h3>尊嚴</h3><p>物質使用不會讓人失去醫療、隱私與被尊重的權利。語言應避免標籤與污名。</p></div><div className="card"><h3>務實</h3><p>從「人現在在哪裡」開始設定可達成目標，先處理最迫切、最可避免的健康風險。</p></div><div className="card"><h3>共同參與</h3><p>服務設計應聽見使用者與社群經驗；有效的支持不是替人做決定，而是增加安全選項與求助可近性。</p></div></div>
<h2 id="services">國際上有哪些實證減害措施？</h2><p>WHO 對注射藥物使用者的綜合性服務建議，包含降低污名與歧視、社群參與，以及針具服務、鴉片類促效劑治療、過量管理、HIV／病毒性肝炎／性傳染感染預防與照護等。2026 年 WHO 亦發布針具與注射器方案的最新操作指引，強調社群領導、人權、公平可近性、服務整合與在地調整。</p><p>不同措施的法律地位與可近性在各國差異很大，因此「國際上有證據」不等於「台灣目前可以用完全相同模式提供」。</p>
<h2 id="stigma">為什麼污名也是健康風險？</h2><p>羞辱與標籤可能讓人延後求助、隱瞞使用、避免篩檢或離開醫療與社福系統。減害因此把「降低求助障礙」視為公共衛生的一部分。網站也會盡量使用「藥物使用者／有物質使用疾患的人」等以人為先的語言，而不是用單一標籤定義一個人。</p>
<h2 id="taiwan">放到台灣情境時，我們會做兩件事</h2><ol><li><strong>把國際證據和台灣法規分開說清楚。</strong> 不把外國方案直接當成台灣可取得服務。</li><li><strong>避免把衛教寫成個人化醫療或法律建議。</strong> 若涉及治療、感染、過量或司法風險，應轉向合格醫療、衛生或法律專業資源。</li></ol>
<div className="notice"><strong>緊急狀況：</strong> 若有人失去反應、呼吸異常、抽搐、胸痛或出現其他可能危及生命的症狀，應立即尋求緊急醫療協助，不要只依賴網路資訊。</div>
<h2 id="sources">主要參考來源</h2><ul className="references"><li><Ref href="https://hri.global/what-is-harm-reduction/">Harm Reduction International — What is Harm Reduction?</Ref></li><li><Ref href="https://www.who.int/teams/global-hiv-hepatitis-and-stis-programmes/populations/people-who-inject-drugs">WHO — People who inject drugs: comprehensive package of services</Ref></li><li><Ref href="https://www.who.int/westernpacific/publications/i/item/9789240116214">WHO — Needle and syringe programmes for people who inject drugs: operational guide (2026)</Ref></li></ul><div className="meta">最後更新：2026-10-05 · 國際內容需依台灣法規、醫療規範與實際服務可近性解讀。</div></article></div></section></SiteShell>}
